project_name: gomangareaderdl

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download

builds:
  - id: gomangareaderdl-build
    main: gomangareaderdl.go
    binary: gomangareaderdl
    env:
      - CGO_ENABLED=1
    goos:
      - windows
#      - linux
#      - darwin
    goarch:
      - amd64

archives:
  - id: gomangareaderdl-archive
    # Builds reference which build instances should be archived in this archive.
    builds:
    - gomangareaderdl-build
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      amd64: 64-bit
      darwin: macOS
    wrap_in_directory: false
    format: gz
    files:
      - none*
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
  algorithm: md5

#signs:
#  - artifacts: checksum

release:
  github:
    owner: francoiscolombo
    name: gomangareaderdl
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: true

changelog:
  skip: false
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - typo
      - (?i)foo
